### ISSUE TITLE
Couldn't make it work in real-time

### ISSUE THREAD

**Issue by mason-stafford** [AniMesuro/rhubarb-lipsync-tp-integration-godot#14]
I wish I could use it with real time voice coming from microphone

**Comment by AniMesuro** [comment]
Sorry for the late response.
I'm afraid this is not possible as it falls beyond the scope of this project.
This addon is simple an gui integration for rhubarb so all lipsync functionality is made through Rhubarb Lip Sync.
Rhubarb requires some processing time, so it's an unavoidable limitation.

I do not know any open source nor commercial approaches for godot to achieve automatic lip sync in real time.
The most I can think of is to make lip flaps based on the db of the current audio sample.

**Comment by mason-stafford** [comment]
Huge thanks for responding,
Let's hope this possibility comes to this nice project.
